<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' Invite and request' => '邀请和申请',
  'Everyone can enter' => '所有人能进入',
  'Invite and request' => '邀请和申请',
  'Only by invite' => '仅被邀请',
  'Private (Invisible)' => '私有(不可见)',
  'Public (Visible)' => '公有(可见)',
  'Visible for all' => '所有人可见',
  'Could not delete user who is a space owner! Name of Space: {spaceName}' => '无法删除用户，用户是版块{spaceName}的主人',
);
