<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accept Invite' => '接受邀请',
  'Become member' => '成为成员',
  'Cancel membership' => '取消成员',
  'Cancel pending membership application' => '取消待定的成员申请',
  'Deny Invite' => '拒绝邀请',
  'Follow' => '关注',
  'Request membership' => '请求成为成员',
  'Unfollow' => '取消关注',
  'You are the owner of this workspace.' => '你是这个版块的拥有者',
  'created by' => '创建人',
);
