<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Space</strong> Modules' => '<strong>模块</strong> 管理',
  'Activated' => '已激活',
  'Are you sure? *ALL* module data for this space will be deleted!' => '你确定吗？ 所有该版块的模块将被删除！',
  'Configure' => '配置',
  'Currently there are no modules available for this space!' => '当前版块没有可用模块！',
  'Disable' => '失效',
  'Enable' => '生效',
  'Enhance this space with modules.' => '为版块添加模块',
  'Modules' => '模块',
);
