<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Add</strong> OEmbed Provider' => '<strong>增加</strong> OEmbed 提供商',
  '<strong>Edit</strong> OEmbed Provider' => '<strong>编辑</strong> OEmbed 提供商',
  'Delete' => '删 除',
  'Save' => '保 存',
  'Url Prefix without http:// or https:// (e.g. youtube.com)' => '不带http://或https://的url前缀(例如 youtube.com)',
  'Use %url% as placeholder for URL. Format needs to be JSON. (e.g. http://www.youtube.com/oembed?url=%url%&format=json)' => '使用%url%作为占位符。需要JSON格式。(例如http://www.youtube.com/oembed?url=%url%&format=json)',
);
